# Generated by Django 4.2.16 on 2024-11-19 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tmdb_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField(null=True)),
                ('description', models.TextField()),
                ('original_language', models.CharField(max_length=50, null=True)),
                ('poster_path', models.TextField(null=True)),
                ('vote_average', models.DecimalField(decimal_places=1, default=0, max_digits=15)),
                ('adult', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieDiary.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieDiary.movie')),
            ],
        ),
    ]
