# Generated by Django 4.2.16 on 2024-11-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movieDiary", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalcomment",
            name="title",
        ),
        migrations.AlterField(
            model_name="journalcomment",
            name="movie_journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="movieDiary.moviejournal",
            ),
        ),
        migrations.AlterField(
            model_name="likedjournal",
            name="movie_journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="movieDiary.moviejournal",
            ),
        ),
        migrations.AlterField(
            model_name="recommended",
            name="movie_journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommends",
                to="movieDiary.moviejournal",
            ),
        ),
    ]
