# Generated by Django 4.2.16 on 2024-11-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movieDiary", "0003_moviejournal_evaluation_moviejournal_hide_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moviejournal",
            name="title",
        ),
    ]
