# Generated by Django 4.2.16 on 2024-11-25 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieDiary', '0006_alter_journalcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviejournal',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movieJournal', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='moviejournal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieJournal', to=settings.AUTH_USER_MODEL),
        ),
    ]
